title: پروژه‌های وبلاگ پاسگاه
description: در این وبلاگ، پروژه‌های html وبلاگ پاسگاه نگهداری می‌شه
url: "https://pasgah.github.io"
baseurl: ""
author: احسان چهری
permalink: /blog/:title
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
