title: وبلاگ من
description: وبلاگ شخصی با پیمایش بی‌نهایت و جستجوی زنده
url: "https://pasgah.github.io"
baseurl: ""
author: نام نویسنده
permalink: /posts/:title/
markdown: kramdown
plugins:
  - jekyll-sitemap
defaults:
  - scope:
      path: "_posts"
    values:
      layout: post
