url: https://indexes.ir

title: وبلاگ ایندکس

description: وبلاگ ایندکس

permalink: /:title

encoding: UTF-8

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      type: "post"
